ARG FEDORA_VERSION=41
ARG KMOD_NAME=nvidia
ARG KMOD_IMAGE=${KMOD_NAME}-kmod
ARG KMOD_TAG=latest
ARG CACHE_IMAGE=${KMOD_IMAGE}:${KMOD_TAG}

FROM ${CACHE_IMAGE} AS kmod-cache
FROM quay.io/fedora-ostree-desktops/base:${FEDORA_VERSION}

RUN dnf install -y \
  https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
  https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

RUN sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/fedora-{updates-archive,cisco-openh264}.repo

COPY --from=kmod-cache /rpms /tmp/akmods/rpms
COPY --from=kmod-cache /info /tmp/akmods/info
COPY --from=kmod-cache /scripts /tmp/akmods/scripts

RUN chmod +x /tmp/akmods/scripts/*.sh && \
  /tmp/akmods/scripts/00-preinstall.sh && \
  /tmp/akmods/scripts/01-install.sh && \
  /tmp/akmods/scripts/02-postinstall.sh
