ARG FEDORA_VERSION=39
ARG NVIDIA_VERSION=545
ARG RPMFUSION_TESTING_ENABLED=false

FROM quay.io/fedora-ostree-desktops/base:${FEDORA_VERSION} AS builder

ARG FEDORA_VERSION
ARG NVIDIA_VERSION
ARG RPMFUSION_TESTING_ENABLED

COPY nvidia/scripts /tmp/scripts
COPY nvidia/nvidia-addons.spec /tmp/nvidia-addons/nvidia-addons.spec
COPY _certs /tmp/certs

ADD https://nvidia.github.io/libnvidia-container/stable/rpm/nvidia-container-toolkit.repo \
    /tmp/nvidia-addons/rpmbuild/SOURCES/nvidia-container-toolkit.repo
ADD https://raw.githubusercontent.com/NVIDIA/dgx-selinux/master/bin/RHEL9/nvidia-container.pp \
    /tmp/nvidia-addons/rpmbuild/SOURCES/nvidia-container.pp

RUN /tmp/scripts/nvidia-setup.sh
RUN /tmp/scripts/nvidia-build.sh

RUN rpm -ql /tmp/nvidia-addons/rpmbuild/RPMS/*/*.rpm


FROM scratch AS artifacts

COPY --from=builder /var/cache /var/cache
COPY --from=builder /tmp/nvidia-addons /tmp/nvidia-addons
COPY --from=builder /tmp/scripts/nvidia-install.sh /tmp/scripts/nvidia-install.sh
COPY --from=builder /tmp/scripts/nvidia-postinstall.sh /tmp/scripts/nvidia-postinstall.sh
