ARG FEDORA_VERSION=40
ARG NVIDIA_VERSION=550
ARG RPMFUSION_TESTING_ENABLED=false
ARG COREOS_KERNEL="N/A"

FROM quay.io/fedora-ostree-desktops/base:${FEDORA_VERSION} AS builder

ARG FEDORA_VERSION
ARG NVIDIA_VERSION
ARG RPMFUSION_TESTING_ENABLED
ARG COREOS_KERNEL

COPY nvidia/scripts /tmp/scripts
COPY nvidia/nvidia-addons.spec /tmp/nvidia-addons/nvidia-addons.spec
COPY nvidia/files/usr/lib/systemd/system/eternal-nvctk-cdi.service /tmp/nvidia-addons/rpmbuild/SOURCES/eternal-nvctk-cdi.service
COPY nvidia/files/usr/lib/systemd/system-preset/01-eternal-nvctk-cdi.preset /tmp/nvidia-addons/rpmbuild/SOURCES/01-eternal-nvctk-cdi.preset
COPY _certs /tmp/certs

RUN chmod +x /tmp/scripts/*.sh
RUN /tmp/scripts/nvidia-setup.sh
RUN /tmp/scripts/nvidia-build.sh
RUN /tmp/scripts/nvidia-addons-build.sh
RUN /tmp/scripts/nvidia-postbuild.sh

RUN rpm -ql /rpms/*.rpm


FROM scratch AS artifacts

COPY --from=builder /rpms /rpms
COPY --from=builder /tmp/scripts/nvidia-install.sh /scripts/install.sh
COPY --from=builder /tmp/scripts/nvidia-postinstall.sh /scripts/postinstall.sh
COPY --from=builder /var/cache/akmods/nvidia-vars /info/nvidia-vars
